### PR TITLE
Fix installation issues for 130 and 131 and some other random stuff

### LINKED ISSUE #74: v1.130 breaks poetry install
immich devs reorganized the pyproject.toml file for machine learning dependenices.

<details>

<summary>diff</summary>

https://github.com/immich-app/immich/blob/v1.129.0/machine-learning/pyproject.toml
https://github.com/immich-app/immich/blob/v1.130.0/machine-learning/pyproject.toml

```diff
diff --git a/129.toml b/130.toml
index fdb0671..a68cd99 100644
--- a/129.toml
+++ b/130.toml
@@ -1,72 +1,79 @@
-[tool.poetry]
+[project]
 name = "machine-learning"
 version = "1.129.0"
 description = ""
-authors = ["Hau Tran <alex.tran1502@gmail.com>"]
+authors = [{ name = "Hau Tran", email = "alex.tran1502@gmail.com" }]
+requires-python = ">=3.10,<4.0"
 readme = "README.md"
-packages = [{include = "app"}]
-
-[tool.poetry.dependencies]
-python = ">=3.10,<4.0"
-insightface = ">=0.7.3,<1.0"
-opencv-python-headless = ">=4.7.0.72,<5.0"
-pillow = ">=9.5.0,<11.0"
-fastapi = ">=0.95.2,<1.0"
-uvicorn = {extras = ["standard"], version = ">=0.22.0,<1.0"}
-pydantic = "^2.0.0"
-pydantic-settings = "^2.5.2"
-aiocache = ">=0.12.1,<1.0"
-rich = ">=13.4.2"
-ftfy = ">=6.1.1"
-python-multipart = ">=0.0.6,<1.0"
-orjson = ">=3.9.5"
-gunicorn = ">=21.1.0"
-huggingface-hub = ">=0.20.1,<1.0"
-tokenizers = ">=0.15.0,<1.0"
-
-[tool.poetry.group.dev.dependencies]
-mypy = ">=1.3.0"
-black = ">=23.3.0"
-pytest = ">=7.3.1"
-locust = ">=2.15.1"
-httpx = ">=0.24.1"
-pytest-asyncio = ">=0.21.0"
-pytest-cov = ">=4.1.0"
-ruff = ">=0.0.272"
-pytest-mock = ">=3.11.1"
-
-[tool.poetry.group.cpu]
-optional = true
-
-[tool.poetry.group.cpu.dependencies]
-onnxruntime = "^1.15.0"
-
-[tool.poetry.group.cuda]
-optional = true
-
-[tool.poetry.group.cuda.dependencies]
-onnxruntime-gpu = {version = "^1.17.0", source = "cuda12"}
-
-[tool.poetry.group.openvino]
-optional = true
-
-[tool.poetry.group.openvino.dependencies]
-onnxruntime-openvino = ">=1.17.1,<1.19.0"
+dependencies = [
+    "aiocache>=0.12.1,<1.0",
+    "fastapi>=0.95.2,<1.0",
+    "ftfy>=6.1.1",
+    "gunicorn>=21.1.0",
+    "huggingface-hub>=0.20.1,<1.0",
+    "insightface>=0.7.3,<1.0",
+    "opencv-python-headless>=4.7.0.72,<5.0",
+    "orjson>=3.9.5",
+    "pillow>=9.5.0,<11.0",
+    "pydantic>=2.0.0,<3",
+    "pydantic-settings>=2.5.2,<3",
+    "python-multipart>=0.0.6,<1.0",
+    "rich>=13.4.2",
+    "tokenizers>=0.15.0,<1.0",
+    "uvicorn[standard]>=0.22.0,<1.0",
+]
+
+[dependency-groups]
+test = [
+    "httpx>=0.24.1",
+    "pytest>=7.3.1",
+    "pytest-asyncio>=0.21.0",
+    "pytest-cov>=4.1.0",
+    "pytest-mock>=3.11.1",
+]
+types = [
+    "types-pyyaml>=6.0.12.20241230",
+    "types-requests>=2.32.0.20250306",
+    "types-setuptools>=75.8.2.20250305",
+    "types-simplejson>=3.20.0.20250218",
+    "types-ujson>=5.10.0.20240515",
+]
+lint = [
+    "black>=23.3.0",
+    "mypy>=1.3.0",
+    "ruff>=0.0.272",
+    { include-group = "types" },
+]
+dev = ["locust>=2.15.1", { include-group = "test" }, { include-group = "lint" }]
+
+[project.optional-dependencies]
+cpu = ["onnxruntime>=1.15.0,<2"]
+cuda = ["onnxruntime-gpu>=1.17.0,<2"]
+openvino = ["onnxruntime-openvino>=1.17.1,<1.19.0"]
+armnn = ["onnxruntime>=1.15.0,<2"]
+rknn = ["onnxruntime>=1.15.0,<2", "rknn-toolkit-lite2>=2.3.0,<3"]
+rocm = []
+
+[tool.uv]
+compile-bytecode = true
+
+[[tool.uv.index]]
+name = "cuda12"
+url = "https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/"
+explicit = true

-[tool.poetry.group.armnn]
-optional = true
+[tool.uv.sources]
+onnxruntime-gpu = { index = "cuda12" }

-[tool.poetry.group.armnn.dependencies]
-onnxruntime = "^1.15.0"
+[tool.hatch.build.targets.sdist]
+include = ["app"]

-[[tool.poetry.source]]
-name = "cuda12"
-url = "https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/"
-priority = "explicit"
+[tool.hatch.build.targets.wheel]
+include = ["app"]

 [build-system]
-requires = ["poetry-core"]
-build-backend = "poetry.core.masonry.api"
+requires = ["hatchling"]
+build-backend = "hatchling.build"

 [tool.mypy]
 python_version = "3.11"
```

</details>

Groups `dev` and `openvino`, etc do not exist anymore, so the `poetry` commands in the install script will fail.

Proposed fix with backward compatibility

```shell
major=$(echo $REPO_TAG | cut -d'.' -f1)
minor=$(echo $REPO_TAG | cut -d'.' -f2)

# Check minor release version
# This only assumes version 1.x though
# For completeness, we might want to check the major version as well in case someone is using old 0.x versions
if [ $minor -gt 129 ]; then
    poetry_args='--no-root --extras'
else
    poetry_args='--no-root --with dev --with'
fi

# Install CUDA parts only when necessary
if [ $isCUDA = true ]; then
    poetry install $poetry_args cuda
elif [ $isCUDA = "openvino" ]; then
    poetry install $poetry_args openvino
else
    poetry install $poetry_args cpu
fi
``` 

To make it easier for you, here is a patch

```patch
diff --git a/install.sh b/install.sh
index aed4764..c3142cd 100755
--- a/install.sh
+++ b/install.sh
@@ -249,13 +249,25 @@ install_immich_machine_learning () {
         poetry update
     fi

+    major=$(echo $REPO_TAG | cut -d'.' -f1)
+    minor=$(echo $REPO_TAG | cut -d'.' -f2)
+
+    # Check minor release version
+    # This only assumes version 1.x though
+    # For completeness, we might want to check the major version as well in case someone is using old 0.x versions
+    if [ $minor -gt 129 ]; then
+        poetry_args='--no-root --extras'
+    else
+        poetry_args='--no-root --with dev --with'
+    fi
+
     # Install CUDA parts only when necessary
     if [ $isCUDA = true ]; then
-        poetry install --no-root --with dev --with cuda
+        poetry install $poetry_args cuda
     elif [ $isCUDA = "openvino" ]; then
-        poetry install --no-root --with dev --with openvino
+        poetry install $poetry_args openvino
     else
-        poetry install --no-root --with dev --with cpu
+        poetry install $poetry_args cpu
     fi

     # Work around for bad poetry config
@@ -422,4 +434,4 @@ create_runtime_env_file

 echo "----------------------------------------------------------------"
 echo "Done. Please install the systemd services to start using Immich."
-echo "----------------------------------------------------------------"
\ No newline at end of file
+echo "----------------------------------------------------------------"
```

Save this file as `fix.patch` inside the `immich-in-lxc` folder, run `patch -p1 < fix.patch` to apply the fix, and you are good to go.

### LINKED ISSUE #76: v1.131 breaking change
Yet another breaking change requires some updates to the scripts.

In the new 131 release, the `machine-learning/app` folder has been refactored into `machine-learning/immich_ml` and the bash script `start.sh` has been dropped in favor of `python -m immich_ml`. As such, the installing script and systemd service are broken.

Based on my previous work in #74, more if's need to be added to the script.

Full patch for `install.sh` from the latest commit. Apply with `patch -p1 < fix.patch`

```diff
diff --git a/install.sh b/install.sh
index aed4764..a69933d 100755
--- a/install.sh
+++ b/install.sh
@@ -98,7 +98,7 @@ review_dependency () {

 review_dependency

-set -xeuo pipefail
+set -xeuo pipefail

 # -------------------
 # Common variables
@@ -109,6 +109,8 @@ INSTALL_DIR_app=$INSTALL_DIR/app
 INSTALL_DIR_ml=$INSTALL_DIR_app/machine-learning
 INSTALL_DIR_geo=$INSTALL_DIR/geodata
 REPO_URL="https://github.com/immich-app/immich"
+MAJOR_VERSION=$(echo $REPO_TAG | cut -d'.' -f1)
+MINOR_VERSION=$(echo $REPO_TAG | cut -d'.' -f2)

 # -------------------
 # Clean previous build
@@ -152,6 +154,7 @@ create_folders
 clone_the_repo () {
     if [ ! -d "$INSTALL_DIR_src" ]; then
         git clone "$REPO_URL" "$INSTALL_DIR_src" --single-branch
+        cd $INSTALL_DIR_src
     else
         cd $INSTALL_DIR_src
         # REMOVE all the change one made to source repo, which is sth not supposed to happen
@@ -160,10 +163,9 @@ clone_the_repo () {
         git checkout main
         # Get updates
         git pull
-        # Set the install version
-        git checkout $REPO_TAG
     fi
-
+    # Set the install version
+    git checkout $REPO_TAG
 }

 clone_the_repo
@@ -187,12 +189,12 @@ install_immich_web_server () {
     cd ..

     cd open-api/typescript-sdk
-    npm ci
+    npm ci
     npm run build
     cd ../..

     cd web
-    npm ci
+    npm ci
     npm run build
     cd ..

@@ -249,22 +251,35 @@ install_immich_machine_learning () {
         poetry update
     fi

+    # Check minor release version
+    # This only assumes version 1.x though
+    # For completeness, we might want to check the major version as well in case someone is using old 0.x versions
+    if [ $MINOR_VERSION -gt 129 ]; then
+        poetry_args='--no-root --extras'
+    else
+        poetry_args='--no-root --with dev --with'
+    fi
+
     # Install CUDA parts only when necessary
     if [ $isCUDA = true ]; then
-        poetry install --no-root --with dev --with cuda
+        poetry install $poetry_args cuda
     elif [ $isCUDA = "openvino" ]; then
-        poetry install --no-root --with dev --with openvino
+        poetry install $poetry_args openvino
     else
-        poetry install --no-root --with dev --with cpu
+        poetry install $poetry_args cpu
     fi

     # Work around for bad poetry config
     pip install "numpy<2" -i $PROXY_POETRY
     )
-
+
     # Copy results
     cd $INSTALL_DIR_src
-    cp -a machine-learning/ann machine-learning/start.sh machine-learning/app $INSTALL_DIR_ml/
+    if [ $MINOR_VERSION -gt 130 ]; then
+        cp -a machine-learning/ann machine-learning/immich_ml $INSTALL_DIR_ml/
+    else
+        cp -a machine-learning/ann machine-learning/start.sh machine-learning/app $INSTALL_DIR_ml/
+    fi
 }

 install_immich_machine_learning
@@ -280,7 +295,11 @@ replace_usr_src () {
     grep -Rl /usr/src | xargs -n1 sed -i -e "s@/usr/src@$INSTALL_DIR@g"
     ln -sf $INSTALL_DIR_app/resources $INSTALL_DIR/
     mkdir -p $INSTALL_DIR/cache
-    sed -i -e "s@\"/cache\"@\"$INSTALL_DIR/cache\"@g" $INSTALL_DIR_ml/app/config.py
+    if [ $MINOR_VERSION -gt 130 ]; then
+        sed -i -e "s@\"/cache\"@\"$INSTALL_DIR/cache\"@g" $INSTALL_DIR_ml/immich_ml/config.py
+    else
+        sed -i -e "s@\"/cache\"@\"$INSTALL_DIR/cache\"@g" $INSTALL_DIR_ml/app/config.py
+    fi
     grep -RlE "\"/build\"|'/build'" | xargs -n1 sed -i -e "s@\"/build\"@\"$INSTALL_DIR_app\"@g" -e "s@'/build'@'$INSTALL_DIR_app'@g"
 }

@@ -371,6 +390,13 @@ cd $INSTALL_DIR_app
 exec node $INSTALL_DIR_app/dist/main "\$@"
 EOF

+if [ $MINOR_VERSION -gt 130 ]; then
+    pkg_name=immich_ml
+else
+    pkg_name=app
+fi
+
+
     # Machine learning
     cat <<EOF > $INSTALL_DIR_ml/start.sh
 #!/bin/bash
@@ -387,14 +413,18 @@ cd $INSTALL_DIR_ml
 : "\${MACHINE_LEARNING_WORKERS:=1}"
 : "\${MACHINE_LEARNING_WORKER_TIMEOUT:=120}"

-exec gunicorn app.main:app \
-        -k app.config.CustomUvicornWorker \
+exec gunicorn $pkg_name.main:app \
+        -k $pkg_name.config.CustomUvicornWorker \
         -w "\$MACHINE_LEARNING_WORKERS" \
         -b "\$MACHINE_LEARNING_HOST":"\$MACHINE_LEARNING_PORT" \
         -t "\$MACHINE_LEARNING_WORKER_TIMEOUT" \
         --log-config-json log_conf.json \
         --graceful-timeout 0
 EOF
+
+if [ $MINOR_VERSION -gt 130 ]; then
+    chmod 775 $INSTALL_DIR_ml/start.sh
+fi
 }

 create_custom_start_script
@@ -422,4 +452,4 @@ create_runtime_env_file

 echo "----------------------------------------------------------------"
 echo "Done. Please install the systemd services to start using Immich."
-echo "----------------------------------------------------------------"
\ No newline at end of file
+echo "----------------------------------------------------------------"
 ```

### PR DESCRIPTION
**Pull request by tautomer**
Fixes #74 
Fixes #76 

1. Fix install.sh for v1.130 and v1.131
2. Fix function `clone_the_repo` when the repo does not already exist in `install.sh`
3. Parallelize `libheif` compilation in `pre-install.sh`
4. Fix `post-install.sh` for v1.131

### CODE REVIEW

File: post-install.sh [hunk 1]
```diff
@@ -7,11 +7,30 @@ set -xeuo pipefail # Make my life easier
...
+# -------------------
+
+load_environment_variables () {
+    # Read the .env file into variables
+    cd $SCRIPT_DIR
+    set -a
+    . ./.env
+    set +a
+}
+
```
Comment (moloroplayer) [inline post-install.sh:22]: load_environment_variables

Comment (moloroplayer) [reply post-install.sh:22]: this Line needs to be added that the variables will be loaded otherwise collum 28 failes because it can't find $REPO_TAG

**Review by moloroplayer — CHANGES_REQUESTED** [review]

**Review by moloroplayer — APPROVED** [review]
Tested now all is Working (Y)

**Comment by tautomer** [comment]
> Tested now all is Working (Y)

Thanks! I also realized that the old machine-learning/start.sh could be updated and reused, so I chose to revert the changes made in post-install.sh. As long as start.sh is updated, the old systemd file will still work.

**Comment by mrgpd-pfevre** [comment]
Hi there I'm also concerned by installing new immich LXC version.
I'm a bit confused with poetry vs uv which one should be used for ML build env ?

**Comment by mrgpd-pfevre** [comment]
I've tried to switch to uv build env, but It brokes my ML service. about some cuda libs not found !
With poerty it was working like a charm for months of update.

**Comment by tautomer** [comment]
> Hi there I'm also concerned by installing new immich LXC version. I'm a bit confused with poetry vs uv which one should be used for ML build env ?

In terms of installing packages, there should not be fundamental difference between these two, with uv being slightly faster based on my tests with immich. The speed up with uv is negligible (about 3 seconds) compared to the time spent on building dependencies and the server itself, so I kept poetry. 

> I've tried to switch to uv build env, but It brokes my ML service. about some cuda libs not found ! With poerty it was working like a charm for months of update.

Sorry, I do not have a device to test CUDA. You just did `uv sync --extra cuda` and the service is broken? I have no idea why this would happen... Maybe you can do a comparison between the packages installed with poetry vs uv. I believe both `poetry install` and `uv sync` relies on the same `pyproject.toml`, which should lead to the same environment.

**Comment by mrgpd-pfevre** [comment]
Thx for your answer and details about poetry vs uv
I just fixed my problem, it was in fact my lxc cgroup settings that were no more in sync with the major device number of my graphic cards after reboot :-/
I have to find a way to fix proxmox nvidia kernel driver to change his device major number.
Regards,

**Comment by scyotech** [comment]
Thanks @tautomer !!!   Beta-ed your 3 commits in my environment and upgraded to v1.131.3 with no problems!  Very much appreciated!

**Comment by Spartan-II-117** [comment]
@loeeeee can this be merged? I also tested it and it worked correctly.

**Comment by loeeeee** [comment]
Thanks for all the time and efforts! :)
